### PR TITLE
fix btn responsive

### PR DESCRIPTION
**Pull request by syauqiahmd**

### CODE REVIEW

**Comment by syauqiahmd** [comment]
sekalian membaiki #35

**Comment by syauqiahmd** [comment]
nang ngini acc ja kah paman mun aing merge

**Comment by FaruqRahmadani** [comment]
### Perubahan
image
Memindah variabel ke dalam file variabel, biar lebih mudah di cari
Didalam commit : https://github.com/FaruqRahmadani/Presensi-Guru-2/pull/37/commits/b6a4c5f4cacb378939ba37a64dd38e6de5f75b8a

**Comment by FaruqRahmadani** [comment]
kalo pian ada yg kd acc, di revert aja kdpp mamangs

**Pull request merged**
